### ISSUE TITLE
Allow configuration also via system properties in addition to environment variables

### ISSUE THREAD

**Issue by kwin** [Netcentric/maven-ext-repos-from-env#19]
Currently the extension can be configured only via environment variables. To ease using it locally with the help of `.mvn/jvm.config` (https://maven.apache.org/configure.html#mvn-jvm-config-file) it should be possible to pass the configuration via system properties alternatively.

**Comment by ghenzler** [comment]
So I suppose the system property would be taken as fallback in case the env variable does not exist? (if the sys property is to take precedence, you would have to add `.mvn/jvm.config` to `.gitignore` which might be problematic for cases when you want to use jvm.config for other use cases)

**Comment by kwin** [comment]
The other way around seems more intuitive as System properties are Java process specific while Environment variables are usually OS wide. Why do you think this would be problematic? The chance for name clashes should be close to zero.
